// web/src/ui/JunglePanel.tsx
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import type { JungleAnimal, PublicPlayer, RoomSnapshot, RoomSettings, SeatKey } from "../shared/types";
import { jungleBoardThemes } from "../lib/constants";
import { ask } from "../lib/rpc";
import { GameClockBar, occupantDisplay, useNow } from "./AppViews";

const ROWS = 9;
const COLS = 7;

const ANIMAL_LABEL: Record<JungleAnimal, string> = {
  rat: "鼠", cat: "猫", dog: "狗", wolf: "狼",
  leopard: "豹", tiger: "虎", lion: "狮", elephant: "象"
};
const ANIMAL_EMOJI: Record<JungleAnimal, string> = {
  rat: "🐀", cat: "🐈", dog: "🐕", wolf: "🐺",
  leopard: "🐆", tiger: "🐅", lion: "🦁", elephant: "🐘"
};
const ANIMAL_RANK: Record<JungleAnimal, number> = {
  rat: 1, cat: 2, dog: 3, wolf: 4, leopard: 5, tiger: 6, lion: 7, elephant: 8
};

function parseCell(cell: string | null | undefined): { side: SeatKey; animal: JungleAnimal } | null {
  if (!cell) return null;
  const [side, animal] = cell.split(":");
  if ((side !== "A" && side !== "B") || !(animal in ANIMAL_RANK)) return null;
  return { side: side as SeatKey, animal: animal as JungleAnimal };
}

function isWater(row: number, col: number) {
  if (row < 3 || row > 5) return false;
  return (col >= 1 && col <= 2) || (col >= 4 && col <= 5);
}
function isDen(row: number, col: number, side: SeatKey) {
  return col === 3 && (side === "A" ? row === 8 : row === 0);
}
function isTrap(row: number, col: number, side: SeatKey) {
  if (side === "A") return (row === 8 && (col === 2 || col === 4)) || (row === 7 && col === 3);
  return (row === 0 && (col === 2 || col === 4)) || (row === 1 && col === 3);
}
function trapOwner(row: number, col: number): SeatKey | null {
  if (isTrap(row, col, "A")) return "A";
  if (isTrap(row, col, "B")) return "B";
  return null;
}

function canCapture(attackerSide: SeatKey, attacker: JungleAnimal, fromR: number, fromC: number, toR: number, toC: number, defender: JungleAnimal) {
  if (trapOwner(toR, toC) === attackerSide) return true;
  if (attacker === "rat" && defender === "elephant") {
    if (isWater(fromR, fromC) && !isWater(toR, toC)) return false;
    return true;
  }
  if (attacker === "elephant" && defender === "rat") return false;
  return ANIMAL_RANK[attacker] >= ANIMAL_RANK[defender];
}

function jumpDest(board: Array<Array<string | null>>, fromR: number, fromC: number, dr: number, dc: number) {
  let r = fromR + dr;
  let c = fromC + dc;
  if (r < 0 || r >= ROWS || c < 0 || c >= COLS || !isWater(r, c)) return null;
  while (r >= 0 && r < ROWS && c >= 0 && c < COLS && isWater(r, c)) {
    if (board[r][c]) return null;
    r += dr;
    c += dc;
  }
  if (r < 0 || r >= ROWS || c < 0 || c >= COLS) return null;
  return { row: r, col: c };
}

function canMoveTo(board: Array<Array<string | null>>, seat: SeatKey, animal: JungleAnimal, fromR: number, fromC: number, toR: number, toC: number, isJump: boolean) {
  if (toR < 0 || toR >= ROWS || toC < 0 || toC >= COLS) return false;
  if (isDen(toR, toC, seat)) return false;
  if (!isJump && isWater(toR, toC) && animal !== "rat") return false;
  const target = board[toR][toC];
  if (!target) return true;
  const def = parseCell(target);
  if (!def || def.side === seat) return false;
  return canCapture(seat, animal, fromR, fromC, toR, toC, def.animal);
}

function legalDests(board: Array<Array<string | null>>, seat: SeatKey, fromR: number, fromC: number) {
  const src = parseCell(board[fromR]?.[fromC]);
  if (!src || src.side !== seat) return [] as Array<{ row: number; col: number }>;
  const dests: Array<{ row: number; col: number }> = [];
  for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const) {
    const r = fromR + dr;
    const c = fromC + dc;
    if (canMoveTo(board, seat, src.animal, fromR, fromC, r, c, false)) dests.push({ row: r, col: c });
  }
  if (src.animal === "lion" || src.animal === "tiger") {
    for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]] as const) {
      const land = jumpDest(board, fromR, fromC, dr, dc);
      if (land && canMoveTo(board, seat, src.animal, fromR, fromC, land.row, land.col, true)) dests.push(land);
    }
  }
  return dests;
}

export function jungleThemeStyle(themeId?: RoomSettings["jungleBoardTheme"]): CSSProperties {
  const theme = jungleBoardThemes.find((item) => item.id === themeId) || jungleBoardThemes[0];
  return {
    "--jungle-board": theme.board,
    "--jungle-land": theme.land,
    "--jungle-water": theme.water,
    "--jungle-trap": theme.trap,
    "--jungle-den": theme.den,
    "--jungle-border": theme.border,
    "--jungle-a-piece": theme.aPiece,
    "--jungle-b-piece": theme.bPiece,
    "--jungle-a-text": theme.aText,
    "--jungle-b-text": theme.bText,
    "--jungle-hover": theme.hover
  } as CSSProperties;
}

function jungleDeltaText(state: NonNullable<RoomSnapshot["jungle"]>, seat: SeatKey) {
  const delta = state.rankedDelta?.[seat] || 0;
  return `${delta >= 0 ? "+" : ""}${delta}`;
}

/** 阵地 + 棋色：A 下方白棋、B 上方黑棋（棋子 CSS 对应浅/深底）。 */
export function jungleSideLabel(seat: SeatKey): string {
  return seat === "A" ? "下方⬇ 白棋⚪" : "上方⬆ 黑棋⚫";
}

/** 对战比分区简写（完整文案在左右座位卡）：⬇ ⚪ / ⬆ ⚫ */
export function jungleSideBrief(seat: SeatKey): string {
  return seat === "A" ? "⬇ ⚪" : "⬆ ⚫";
}

export function JungleScore({ room }: { room: RoomSnapshot }) {
  const state = room.jungle;
  if (!state) {
    const bothReady = room.ready.A && room.ready.B;
    return <p className="settlement-placeholder">{bothReady ? "正在随机先手" : "等待准备"}</p>;
  }
  return (
    <div className="jungle-score-mini">
      <span className="jungle-score-side">
        <em>玩家 A</em>
        <b>{jungleSideBrief("A")}</b>
      </span>
      <span className="jungle-score-side">
        <em>玩家 B</em>
        <b>{jungleSideBrief("B")}</b>
      </span>
      {room.settings.enableRanked && state.rankedDelta && (
        <span className="jungle-live-rank">白 {jungleDeltaText(state, "A")} / 黑 {jungleDeltaText(state, "B")}</span>
      )}
      <strong>{state.ended ? room.resultText || "对局结束" : `轮到 ${jungleSideLabel(state.turn)}`}</strong>
    </div>
  );
}

export function JunglePanel({ room, me, onError }: { room: RoomSnapshot; me: PublicPlayer; onError: (message: string) => void }) {
  const state = room.jungle;
  const boardTheme = jungleThemeStyle(room.settings.jungleBoardTheme);
  const [busy, setBusy] = useState(false);
  const [selected, setSelected] = useState<{ row: number; col: number } | null>(null);
  const mySeat = room.seats.A?.id === me.id ? "A" : room.seats.B?.id === me.id ? "B" : null;

  useEffect(() => {
    setSelected(null);
  }, [state?.moveCount, room.phase]);

  async function act(event: string, payload: unknown = {}) {
    if (busy) return;
    setBusy(true);
    try {
      await ask(event, payload);
    } catch (error) {
      onError(error instanceof Error ? error.message : "操作失败");
    } finally {
      setBusy(false);
    }
  }

  const board = useMemo(
    () => state?.board || Array.from({ length: ROWS }, () => Array.from({ length: COLS }, () => null as string | null)),
    [state?.board]
  );

  const isMyTurn = Boolean(mySeat && state && state.turn === mySeat && room.phase === "choosing" && !state.ended && !state.resignRequest && !state.undoRequest);
  const destKeys = useMemo(() => {
    if (!isMyTurn || !selected || !mySeat) return new Set<string>();
    return new Set(legalDests(board, mySeat, selected.row, selected.col).map((p) => `${p.row}-${p.col}`));
  }, [board, isMyTurn, selected, mySeat]);

  function onCellClick(row: number, col: number) {
    if (!isMyTurn || !mySeat || busy) return;
    const key = `${row}-${col}`;
    if (selected && destKeys.has(key)) {
      const from = selected;
      setSelected(null);
      act("jungle:move", { fromRow: from.row, fromCol: from.col, toRow: row, toCol: col });
      return;
    }
    const piece = parseCell(board[row][col]);
    if (piece && piece.side === mySeat) {
      if (selected && selected.row === row && selected.col === col) {
        setSelected(null);
      } else {
        setSelected({ row, col });
      }
      return;
    }
    setSelected(null);
  }

  const turnName = state?.turn === "A" ? occupantDisplay(room.seats.A) : occupantDisplay(room.seats.B);
  const waitingForReady = room.phase === "ready" && Boolean(room.seats.A && room.seats.B);
  const drawingFirst = waitingForReady && room.ready.A && room.ready.B;
  const myReady = mySeat ? room.ready[mySeat] : false;
  const undoLimit = room.settings.jungleUndoLimit ?? 0;
  const undoRequest = state?.undoRequest;
  const undoToMe = Boolean(mySeat && undoRequest?.toSeat === mySeat);
  const undoFromMe = Boolean(mySeat && undoRequest?.fromSeat === mySeat);
  const undoFromName = undoRequest ? occupantDisplay(room.seats[undoRequest.fromSeat]) : "";
  const now = useNow(1000, Boolean(undoRequest));
  const undoSecondsLeft = undoRequest ? Math.max(0, Math.ceil((undoRequest.expiresAt - now) / 1000)) : 0;
  const myUndoCount = mySeat ? (state?.undoCount?.[mySeat] ?? 0) : 0;
  const canRequestUndo = Boolean(
    state && mySeat && room.phase === "choosing" && !state.ended && !state.undoRequest && !state.resignRequest &&
    state.turn === mySeat && state.moveCount >= 2 && myUndoCount < undoLimit
  );
  const resignRequest = state?.resignRequest;
  const resignToMe = Boolean(mySeat && resignRequest?.toSeat === mySeat);
  const resignFromMe = Boolean(mySeat && resignRequest?.fromSeat === mySeat);
  const resignFromName = resignRequest ? occupantDisplay(room.seats[resignRequest.fromSeat]) : "";
  const canRequestResign = Boolean(state && mySeat && room.phase === "choosing" && !state.ended && !state.undoRequest && !state.resignRequest);

  let statusHint: string;
  if (!room.seats.A || !room.seats.B) {
    statusHint = "等待两个战斗席坐满。";
  } else if (drawingFirst) {
    statusHint = "正在随机先手...";
  } else if (waitingForReady) {
    statusHint = "双方准备后随机决定谁先手；A 执下方白棋⚪，B 执上方黑棋⚫。";
  } else if (state?.ended) {
    statusHint = room.resultText || "对局结束";
  } else if (isMyTurn) {
    statusHint = selected ? "点击目标格走子。" : "点击想要移动的棋子。";
  } else if (mySeat) {
    statusHint = `轮到对方（ ${turnName} ）走子。`;
  } else {
    statusHint = `轮到 ${turnName} 走子。`;
  }

  return (
    <div className="jungle-panel">
      <div className="jungle-head">
        <div>
          <h3>🦁 斗兽棋</h3>
          <p className="hint">{statusHint}</p>
        </div>
        {state && (
          <div className="jungle-turn-card">
            <span>轮到 {jungleSideLabel(state.turn)}</span>
            {room.settings.enableRanked && state.rankedDelta && (
              <small>本局排位：白 {jungleDeltaText(state, "A")} / 黑 {jungleDeltaText(state, "B")}</small>
            )}
          </div>
        )}
      </div>
      {waitingForReady && (
        <div className={`jungle-ready-card ${drawingFirst ? "drawing" : ""}`}>
          <div className="jungle-draw-animation" aria-hidden="true">
            <span>🦁</span>
            <span>🐘</span>
            <span>🐯</span>
          </div>
          <div>
            <strong>{drawingFirst ? "抽签中..." : myReady ? "你已准备" : "准备开始"}</strong>
            <p className="hint">A：{room.ready.A ? "已准备" : "未准备"} · B：{room.ready.B ? "已准备" : "未准备"}</p>
          </div>
          {mySeat && !myReady && !drawingFirst && <button className="primary" disabled={busy} onClick={() => act("jungle:ready")}>准备</button>}
          {mySeat && myReady && !drawingFirst && <button disabled>等待对方</button>}
        </div>
      )}
      {state?.ended && mySeat && room.phase === "result" && (
        <button className="primary jungle-restart-button" disabled={busy} onClick={() => act("jungle:restart")}>再来一局</button>
      )}
      {undoRequest && (
        <div className={`jungle-request-card ${undoToMe ? "needs-action" : ""}`}>
          <div>
            <strong>{undoFromMe ? "已申请悔棋" : `${undoFromName} 申请悔棋`}</strong>
            <p className="hint">{undoFromMe ? `等待对方确认，${undoSecondsLeft} 秒后自动拒绝。` : `同意后棋局回退 2 手，${undoSecondsLeft} 秒后自动拒绝。`}</p>
          </div>
          {undoToMe && (
            <div className="jungle-request-actions">
              <button className="primary" disabled={busy} onClick={() => act("jungle:undoRespond", { accept: true })}>同意悔棋</button>
              <button className="soft-button" disabled={busy} onClick={() => act("jungle:undoRespond", { accept: false })}>拒绝</button>
            </div>
          )}
        </div>
      )}
      {resignRequest && (
        <div className={`jungle-request-card ${resignToMe ? "needs-action" : ""}`}>
          <div>
            <strong>{resignFromMe ? "已申请认输" : `${resignFromName} 申请认输`}</strong>
            <p className="hint">{resignFromMe ? "等待对方确认；对局状态会保持不变。" : "你可以同意结束本局，或拒绝后继续下棋。"}</p>
          </div>
          {resignToMe && (
            <div className="jungle-request-actions">
              <button className="primary" disabled={busy} onClick={() => act("jungle:resignRespond", { accept: true })}>同意认输</button>
              <button className="soft-button" disabled={busy} onClick={() => act("jungle:resignRespond", { accept: false })}>拒绝，继续下棋</button>
            </div>
          )}
        </div>
      )}
      {(canRequestUndo || canRequestResign) && (
        <div className="jungle-risk-actions">
          {canRequestUndo && (
            <button className="soft-button" disabled={busy} onClick={() => act("jungle:undoRequest")}>申请悔棋<br />本局剩 {undoLimit - myUndoCount} 次</button>
          )}
          {canRequestResign && <button className="soft-button danger-soft" disabled={busy} onClick={() => act("jungle:resignRequest")}>申请认输</button>}
        </div>
      )}
      <GameClockBar
        room={room}
        state={state ? { turn: state.turn, blackSeat: "A", ended: state.ended, moveDeadlineAt: state.moveDeadlineAt, clockDeadlineAt: state.clockDeadlineAt, clockRemaining: state.clockRemaining } : undefined}
        moveSeconds={room.settings.jungleMoveSeconds}
        gameMinutes={room.settings.jungleGameMinutes}
        labels={{ primary: "下方⬇ 白", secondary: "上方⬆ 黑" }}
      />
      <div className="jungle-board" role="grid" aria-label="斗兽棋棋盘" style={boardTheme}>
        {board.map((row, rowIndex) => row.map((cell, colIndex) => {
          const key = `${rowIndex}-${colIndex}`;
          const piece = parseCell(cell);
          const water = isWater(rowIndex, colIndex);
          const denA = isDen(rowIndex, colIndex, "A");
          const denB = isDen(rowIndex, colIndex, "B");
          const trapA = isTrap(rowIndex, colIndex, "A");
          const trapB = isTrap(rowIndex, colIndex, "B");
          const isSelected = Boolean(selected && selected.row === rowIndex && selected.col === colIndex);
          const isDest = destKeys.has(key);
          const isLastFrom = Boolean(state?.lastFrom && state.lastFrom.row === rowIndex && state.lastFrom.col === colIndex);
          const isLastTo = Boolean(state?.lastTo && state.lastTo.row === rowIndex && state.lastTo.col === colIndex);
          const terrain = water ? "water" : denA || denB ? "den" : trapA || trapB ? "trap" : "land";
          return (
            <button
              type="button"
              key={key}
              className={[
                "jungle-cell",
                terrain,
                isSelected ? "selected" : "",
                isDest ? "legal" : "",
                isLastFrom ? "last-from" : "",
                isLastTo ? "last-to" : ""
              ].filter(Boolean).join(" ")}
              disabled={!isMyTurn}
              onClick={() => onCellClick(rowIndex, colIndex)}
              aria-label={`第 ${rowIndex + 1} 行第 ${colIndex + 1} 列${piece ? `，${piece.side}方${ANIMAL_LABEL[piece.animal]}` : ""}`}
            >
              {(denA || denB) && <span className="jungle-terrain-mark" aria-hidden="true">穴</span>}
              {(trapA || trapB) && !piece && <span className="jungle-terrain-mark trap-mark" aria-hidden="true">陷</span>}
              {water && !piece && <span className="jungle-terrain-mark water-mark" aria-hidden="true">～</span>}
              {piece && (
                <span className={`jungle-piece side-${piece.side}`} title={ANIMAL_LABEL[piece.animal]} aria-hidden="true">
                  {ANIMAL_EMOJI[piece.animal]}
                </span>
              )}
            </button>
          );
        }))}
      </div>
      <div className="jungle-rules-hint hint">
        <p className="jungle-rank-line" aria-label="等级：象大于狮大于虎大于豹大于狼大于狗大于猫大于鼠">
          <span className="jungle-rank-label">等级</span>
          {(["elephant", "lion", "tiger", "leopard", "wolf", "dog", "cat", "rat"] as const).map((animal, index) => (
            <span key={animal} className="jungle-rank-item">
              {index > 0 && <span className="jungle-rank-gt" aria-hidden="true">&gt;</span>}
              <span className="jungle-rank-icon" title={ANIMAL_LABEL[animal]}>{ANIMAL_EMOJI[animal]}</span>
            </span>
          ))}
        </p>
        <p>
          🐀 可吃 🐘（不能从水中上岸吃），🐘 不能吃 🐀；仅 🐀 可入水；🦁🐅 可跳河（河中有 🐀 则不能跳）；先入对方兽穴或令对方无子可走者胜。
          敌兽进入己方陷阱，可被任意己方兽吃掉。
        </p>
      </div>
    </div>
  );
}

// web/src/ui/games/JunglePanel.svelte
<script lang="ts">
  // 源：ui/JunglePanel.tsx
  import type { RoomSnapshot, PublicPlayer } from "../../shared/types";
  import { ask } from "../../lib/rpc";
  import { occupantDisplay, jungleDeltaText, jungleSideLabel, jungleThemeStyle } from "../../lib/gameDisplay";
  import { ANIMAL_EMOJI, ANIMAL_LABEL, COLS, ROWS, isDen, isTrap, isWater, legalDests, parseCell } from "../../lib/jungleRules";
  import { useNow } from "../../lib/useNow.svelte";
  import { styleString } from "../../lib/style";
  import GameClockBar from "../shell/GameClockBar.svelte";

  let { room, me, onError }: { room: RoomSnapshot; me: PublicPlayer; onError: (message: string) => void } = $props();

  const gameState = $derived(room.jungle);
  const boardTheme = $derived(styleString(jungleThemeStyle(room.settings.jungleBoardTheme)));
  let busy = $state(false);
  let selected = $state<{ row: number; col: number } | null>(null);
  const mySeat = $derived(room.seats.A?.id === me.id ? "A" : room.seats.B?.id === me.id ? "B" : null);

  $effect(() => {
    void gameState?.moveCount;
    void room.phase;
    selected = null;
  });

  async function act(event: string, payload: unknown = {}) {
    if (busy) return;
    busy = true;
    try {
      await ask(event, payload);
    } catch (error) {
      onError(error instanceof Error ? error.message : "操作失败");
    } finally {
      busy = false;
    }
  }

  const board = $derived(gameState?.board || Array.from({ length: ROWS }, () => Array.from({ length: COLS }, () => null as string | null)));
  const isMyTurn = $derived(Boolean(mySeat && gameState && gameState.turn === mySeat && room.phase === "choosing" && !gameState.ended && !gameState.resignRequest && !gameState.undoRequest));
  const destKeys = $derived.by(() => {
    if (!isMyTurn || !selected || !mySeat) return new Set<string>();
    return new Set(legalDests(board, mySeat, selected.row, selected.col).map((p) => `${p.row}-${p.col}`));
  });

  function onCellClick(row: number, col: number) {
    if (!isMyTurn || !mySeat || busy) return;
    const key = `${row}-${col}`;
    if (selected && destKeys.has(key)) {
      const from = selected;
      selected = null;
      act("jungle:move", { fromRow: from.row, fromCol: from.col, toRow: row, toCol: col });
      return;
    }
    const piece = parseCell(board[row][col]);
    if (piece && piece.side === mySeat) {
      selected = selected && selected.row === row && selected.col === col ? null : { row, col };
      return;
    }
    selected = null;
  }

  const turnName = $derived(gameState?.turn === "A" ? occupantDisplay(room.seats.A) : occupantDisplay(room.seats.B));
  const waitingForReady = $derived(room.phase === "ready" && Boolean(room.seats.A && room.seats.B));
  const drawingFirst = $derived(waitingForReady && room.ready.A && room.ready.B);
  const myReady = $derived(mySeat ? room.ready[mySeat] : false);
  const undoLimit = $derived(room.settings.jungleUndoLimit ?? 0);
  const undoRequest = $derived(gameState?.undoRequest);
  const undoToMe = $derived(Boolean(mySeat && undoRequest?.toSeat === mySeat));
  const undoFromMe = $derived(Boolean(mySeat && undoRequest?.fromSeat === mySeat));
  const undoFromName = $derived(undoRequest ? occupantDisplay(room.seats[undoRequest.fromSeat]) : "");
  const now = useNow(() => 1000, () => Boolean(undoRequest));
  const undoSecondsLeft = $derived(undoRequest ? Math.max(0, Math.ceil((undoRequest.expiresAt - now.value) / 1000)) : 0);
  const myUndoCount = $derived(mySeat ? (gameState?.undoCount?.[mySeat] ?? 0) : 0);
  const canRequestUndo = $derived(Boolean(
    gameState && mySeat && room.phase === "choosing" && !gameState.ended && !gameState.undoRequest && !gameState.resignRequest &&
    gameState.turn === mySeat && gameState.moveCount >= 2 && myUndoCount < undoLimit
  ));
  const resignRequest = $derived(gameState?.resignRequest);
  const resignToMe = $derived(Boolean(mySeat && resignRequest?.toSeat === mySeat));
  const resignFromMe = $derived(Boolean(mySeat && resignRequest?.fromSeat === mySeat));
  const resignFromName = $derived(resignRequest ? occupantDisplay(room.seats[resignRequest.fromSeat]) : "");
  const canRequestResign = $derived(Boolean(gameState && mySeat && room.phase === "choosing" && !gameState.ended && !gameState.undoRequest && !gameState.resignRequest));

  const statusHint = $derived.by(() => {
    if (!room.seats.A || !room.seats.B) return "等待两个战斗席坐满。";
    if (drawingFirst) return "正在随机先手...";
    if (waitingForReady) return "双方准备后随机决定谁先手；A 执下方白棋⚪，B 执上方黑棋⚫。";
    if (gameState?.ended) return room.resultText || "对局结束";
    if (isMyTurn) return selected ? "点击目标格走子。" : "点击想要移动的棋子。";
    if (mySeat) return `轮到对方（ ${turnName} ）走子。`;
    return `轮到 ${turnName} 走子。`;
  });

  const rankOrder = ["elephant", "lion", "tiger", "leopard", "wolf", "dog", "cat", "rat"] as const;
</script>

<div class="jungle-panel">
  <div class="jungle-head">
    <div>
      <h3>🦁 斗兽棋</h3>
      <p class="hint">{statusHint}</p>
    </div>
    {#if gameState}
      <div class="jungle-turn-card">
        <span>轮到 {jungleSideLabel(gameState.turn)}</span>
        {#if room.settings.enableRanked && gameState.rankedDelta}<small>本局排位：白 {jungleDeltaText(gameState, "A")} / 黑 {jungleDeltaText(gameState, "B")}</small>{/if}
      </div>
    {/if}
  </div>
  {#if waitingForReady}
    <div class={`jungle-ready-card ${drawingFirst ? "drawing" : ""}`}>
      <div class="jungle-draw-animation" aria-hidden="true"><span>🦁</span><span>🐘</span><span>🐯</span></div>
      <div>
        <strong>{drawingFirst ? "抽签中..." : myReady ? "你已准备" : "准备开始"}</strong>
        <p class="hint">A：{room.ready.A ? "已准备" : "未准备"} · B：{room.ready.B ? "已准备" : "未准备"}</p>
      </div>
      {#if mySeat && !myReady && !drawingFirst}<button class="primary" disabled={busy} onclick={() => act("jungle:ready")}>准备</button>{/if}
      {#if mySeat && myReady && !drawingFirst}<button disabled>等待对方</button>{/if}
    </div>
  {/if}
  {#if gameState?.ended && mySeat && room.phase === "result"}
    <button class="primary jungle-restart-button" disabled={busy} onclick={() => act("jungle:restart")}>再来一局</button>
  {/if}
  {#if undoRequest}
    <div class={`jungle-request-card ${undoToMe ? "needs-action" : ""}`}>
      <div>
        <strong>{undoFromMe ? "已申请悔棋" : `${undoFromName} 申请悔棋`}</strong>
        <p class="hint">{undoFromMe ? `等待对方确认，${undoSecondsLeft} 秒后自动拒绝。` : `同意后棋局回退 2 手，${undoSecondsLeft} 秒后自动拒绝。`}</p>
      </div>
      {#if undoToMe}
        <div class="jungle-request-actions">
          <button class="primary" disabled={busy} onclick={() => act("jungle:undoRespond", { accept: true })}>同意悔棋</button>
          <button class="soft-button" disabled={busy} onclick={() => act("jungle:undoRespond", { accept: false })}>拒绝</button>
        </div>
      {/if}
    </div>
  {/if}
  {#if resignRequest}
    <div class={`jungle-request-card ${resignToMe ? "needs-action" : ""}`}>
      <div>
        <strong>{resignFromMe ? "已申请认输" : `${resignFromName} 申请认输`}</strong>
        <p class="hint">{resignFromMe ? "等待对方确认；对局状态会保持不变。" : "你可以同意结束本局，或拒绝后继续下棋。"}</p>
      </div>
      {#if resignToMe}
        <div class="jungle-request-actions">
          <button class="primary" disabled={busy} onclick={() => act("jungle:resignRespond", { accept: true })}>同意认输</button>
          <button class="soft-button" disabled={busy} onclick={() => act("jungle:resignRespond", { accept: false })}>拒绝，继续下棋</button>
        </div>
      {/if}
    </div>
  {/if}
  {#if canRequestUndo || canRequestResign}
    <div class="jungle-risk-actions">
      {#if canRequestUndo}<button class="soft-button" disabled={busy} onclick={() => act("jungle:undoRequest")}>申请悔棋<br />本局剩 {undoLimit - myUndoCount} 次</button>{/if}
      {#if canRequestResign}<button class="soft-button danger-soft" disabled={busy} onclick={() => act("jungle:resignRequest")}>申请认输</button>{/if}
    </div>
  {/if}
  <GameClockBar
    {room}
    state={gameState ? { turn: gameState.turn, blackSeat: "A", ended: gameState.ended, moveDeadlineAt: gameState.moveDeadlineAt, clockDeadlineAt: gameState.clockDeadlineAt, clockRemaining: gameState.clockRemaining } : undefined}
    moveSeconds={room.settings.jungleMoveSeconds}
    gameMinutes={room.settings.jungleGameMinutes}
    labels={{ primary: "下方⬇ 白", secondary: "上方⬆ 黑" }}
  />
  <div class="jungle-board" role="grid" aria-label="斗兽棋棋盘" style={boardTheme}>
    {#each board as row, rowIndex (rowIndex)}
      {#each row as cell, colIndex (colIndex)}
        {@const key = `${rowIndex}-${colIndex}`}
        {@const piece = parseCell(cell)}
        {@const water = isWater(rowIndex, colIndex)}
        {@const denA = isDen(rowIndex, colIndex, "A")}
        {@const denB = isDen(rowIndex, colIndex, "B")}
        {@const trapA = isTrap(rowIndex, colIndex, "A")}
        {@const trapB = isTrap(rowIndex, colIndex, "B")}
        {@const isSelected = Boolean(selected && selected.row === rowIndex && selected.col === colIndex)}
        {@const isDest = destKeys.has(key)}
        {@const isLastFrom = Boolean(gameState?.lastFrom && gameState.lastFrom.row === rowIndex && gameState.lastFrom.col === colIndex)}
        {@const isLastTo = Boolean(gameState?.lastTo && gameState.lastTo.row === rowIndex && gameState.lastTo.col === colIndex)}
        {@const terrain = water ? "water" : denA || denB ? "den" : trapA || trapB ? "trap" : "land"}
        <button
          type="button"
          class={["jungle-cell", terrain, isSelected ? "selected" : "", isDest ? "legal" : "", isLastFrom ? "last-from" : "", isLastTo ? "last-to" : ""].filter(Boolean).join(" ")}
          disabled={!isMyTurn}
          onclick={() => onCellClick(rowIndex, colIndex)}
          aria-label={`第 ${rowIndex + 1} 行第 ${colIndex + 1} 列${piece ? `，${piece.side}方${ANIMAL_LABEL[piece.animal]}` : ""}`}
        >
          {#if denA || denB}<span class="jungle-terrain-mark" aria-hidden="true">穴</span>{/if}
          {#if (trapA || trapB) && !piece}<span class="jungle-terrain-mark trap-mark" aria-hidden="true">陷</span>{/if}
          {#if water && !piece}<span class="jungle-terrain-mark water-mark" aria-hidden="true">～</span>{/if}
          {#if piece}<span class={`jungle-piece side-${piece.side}`} title={ANIMAL_LABEL[piece.animal]} aria-hidden="true">{ANIMAL_EMOJI[piece.animal]}</span>{/if}
        </button>
      {/each}
    {/each}
  </div>
  <div class="jungle-rules-hint hint">
    <p class="jungle-rank-line" aria-label="等级：象大于狮大于虎大于豹大于狼大于狗大于猫大于鼠">
      <span class="jungle-rank-label">等级</span>
      {#each rankOrder as animal, index (animal)}
        <span class="jungle-rank-item">
          {#if index > 0}<span class="jungle-rank-gt" aria-hidden="true">&gt;</span>{/if}
          <span class="jungle-rank-icon" title={ANIMAL_LABEL[animal]}>{ANIMAL_EMOJI[animal]}</span>
        </span>
      {/each}
    </p>
    <p>
      🐀 可吃 🐘（不能从水中上岸吃），🐘 不能吃 🐀；仅 🐀 可入水；🦁🐅 可跳河（河中有 🐀 则不能跳）；先入对方兽穴或令对方无子可走者胜。
      敌兽进入己方陷阱，可被任意己方兽吃掉。
    </p>
  </div>
</div>
